# Heart Attack Risk Detection - Data Preprocessing

In this notebook, you will find some actions made on the data. The goal is preparing the data to train machine learning models.

In [48]:
import sys
sys.path.append("../src")

import data.make_dataset as data
import data.preprocessing as prep

import importlib
importlib.reload(data)
importlib.reload(prep)

In [50]:
# Load data
df = data.load_dataset("../data/raw/dataset.csv")
df.head()

,patientid,age,gender,chestpain,restingBP,serumcholestrol,fastingbloodsugar,restingrelectro,maxheartrate,exerciseangia,oldpeak,slope,noofmajorvessels,target
0,103368,53,1,2,171,0,0,1,147,0,5.3,3,3,1
1,119250,40,1,0,94,229,0,1,115,0,3.7,1,1,0
2,119372,49,1,2,133,142,0,0,202,1,5.0,1,0,0
3,132514,43,1,0,138,295,1,1,153,0,3.2,2,2,1
4,146211,31,1,1,199,0,0,2,136,0,5.3,3,2,1

## Cleaning data

First, we will drop some columns that are not necessary (patient ID).

In [51]:
# Drop unnecessary columns
df = prep.drop_columns(df, ["patientid"])
df

,age,gender,chestpain,restingBP,serumcholestrol,fastingbloodsugar,restingrelectro,maxheartrate,exerciseangia,oldpeak,slope,noofmajorvessels,target
0,53,1,2,171,0,0,1,147,0,5.3,3,3,1
1,40,1,0,94,229,0,1,115,0,3.7,1,1,0
2,49,1,2,133,142,0,0,202,1,5.0,1,0,0
3,43,1,0,138,295,1,1,153,0,3.2,2,2,1
4,31,1,1,199,0,0,2,136,0,5.3,3,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,48,1,2,139,349,0,2,183,1,5.6,2,2,1
996,47,1,3,143,258,1,1,98,1,5.7,1,0,0
997,69,1,0,156,434,1,0,196,0,1.4,3,1,1
998,45,1,1,186,417,0,1,117,1,5.9,3,2,1
999,25,1,0,158,270,0,0,143,1,4.7,0,0,0

## Feature engineering

Since there are no missing values nor non-numerical values, we can directly store our dataset after being processed.

In [52]:
df.dtypes

age                    int64
gender                 int64
chestpain              int64
restingBP              int64
serumcholestrol        int64
fastingbloodsugar      int64
restingrelectro        int64
maxheartrate           int64
exerciseangia          int64
oldpeak              float64
slope                  int64
noofmajorvessels       int64
target                 int64
dtype: object

Now, dataset is ready to train models. Let's save it.

In [53]:
prep.save_dataset(df, "dataset-processed.csv")